version: "3.7"

services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"
    environment:
      GRID_MAX_SESSION: 5
      GRID_BROWSER_TIMEOUT: 60
      GRID_TIMEOUT: 60

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
# Uncomment if you want to add Appium (for mobile testing)
#  appium:
#    image: appium/appium
#    container_name: appium
#    ports:
#      - "4723:4723"
#    volumes:
#      - ./app:/app
#    command: appium
